{% set name = "pigz" %}
{% set version = "2.3.4" %}
{% set sha256 = "6f031fa40bc15b1d80d502ff91f83ba14f4b079e886bfb83221374f7bf5c8f9a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://zlib.net/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}        # [unix]
    - {{ compiler("m2w64_c") }}  # [win]
    - posix                      # [win]
  host:
    - pthreads-win32             # [win]
    - zlib
  run:
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
    - pigz -h
    - unpigz -h

about:
  home: https://zlib.net/pigz/
  license: zlib
  license_family: other
  license_file: README
  summary: Parallel implementation of gzip
  description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional
    replacement for gzip that exploits multiple processors and multiple cores
    to the hilt when compressing data.
  doc_url: https://zlib.net/pigz/pigz.pdf

extra:
  recipe-maintainers:
    - epruesse
