{% set version = "2.8" %}
{% set sha256 = "2f7f6a6986996d21cb8658535fff95f1c7107ddce22b5324f4b41890e2904706" %}

package:
  name: pigz
  version: {{ version }}

source:
  url: https://github.com/madler/pigz/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}        # [unix]
    - {{ compiler("m2w64_c") }}  # [win]
    - posix                      # [win]
    - make                       # [unix]
  host:
    - pthreads-win32             # [win]
    - zlib

test:
  commands:
    - pigz -h
    - unpigz -h

about:
  home: https://zlib.net/pigz/
  license: Zlib
  license_family: other
  license_file: README
  summary: Parallel implementation of gzip
  description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional
    replacement for gzip that exploits multiple processors and multiple cores
    to the hilt when compressing data.
  doc_url: https://zlib.net/pigz/pigz.pdf

extra:
  recipe-maintainers:
    - epruesse
    - mfansler 
    - martin-g
