{% set name = "pigz" %}
{% set version = "2.4" %}
{% set sha256 = "a4f816222a7b4269bd232680590b579ccc72591f1bb5adafcd7208ca77e14f73" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://zlib.net/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python           # [win]
    - vc 9             # [win and py27]
    - vc 10            # [win and py34]
    - vc 14            # [win and py>=35]
    - posix            # [win]
    - pthreads-win32   # [win]
    - m2w64-toolchain  # [win]
    - {{ compiler('c') }}
    - zlib
  run:
    - vc 9             # [win and py27]
    - vc 10            # [win and py34]
    - vc 14            # [win and py>=35]
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
    - pigz -h
    - unpigz -h

about:
  home: https://zlib.net/pigz/
  license: zlib
  license_family: other
  license_file: README
  summary: Parallel implementation of gzip
  description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional
    replacement for gzip that exploits multiple processors and multiple cores
    to the hilt when compressing data.
  doc_url: https://zlib.net/pigz/pigz.pdf

extra:
  recipe-maintainers:
    - epruesse
    - mariusvniekerk
