{% set version = "2.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: pigz
  version: {{ version }}

source:
  url: https://github.com/madler/pigz/archive/v{{ version }}.tar.gz
  sha256: 2f7f6a6986996d21cb8658535fff95f1c7107ddce22b5324f4b41890e2904706

build:
  number: 1
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler("c") }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler("m2w64_c") }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - m2-base                    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - zlib

test:
  commands:
    - pigz -h
    - unpigz -h

about:
  home: https://zlib.net/pigz/
  license: Zlib
  license_family: other
  license_file: README
  summary: Parallel implementation of gzip
  description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional
    replacement for gzip that exploits multiple processors and multiple cores
    to the hilt when compressing data.
  doc_url: https://zlib.net/pigz/pigz.pdf

extra:
  recipe-maintainers:
    - epruesse
    - mfansler 
    - martin-g
