{% set name = "pigz" %}
{% set version = "2.7" %}
{% set sha256 = "d2045087dae5e9482158f1f1c0f21c7d3de6f7cdc7cc5848bdabda544e69aa58" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/madler/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}        # [unix]
    - {{ compiler("m2w64_c") }}  # [win]
    - posix                      # [win]
  host:
    - pthreads-win32             # [win]
    - zlib
  run:
    - zlib

test:
  commands:
    - pigz -h
    - unpigz -h

about:
  home: https://zlib.net/pigz/
  license: zlib
  license_family: other
  license_file: README
  summary: Parallel implementation of gzip
  description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional
    replacement for gzip that exploits multiple processors and multiple cores
    to the hilt when compressing data.
  doc_url: https://zlib.net/pigz/pigz.pdf

extra:
  recipe-maintainers:
    - epruesse
