travis:
  secure:
    BINSTAR_TOKEN: 4WKOqmhnbNKAZUD68d9gZbQrjHd/jJLQgy4Txng+Qh+dNTkbUoDpQWmldl0+3RnYvA8mx+cDuQWdZu5w4P+6e7dQRqz2BLqg+z2Ygt4nJq/qxyUJAtr/l5HhyjzQA68y4VW2hF6rMF3oUpwo1dUNuYvtyfwzvOblwUZ9qvaRG6ryLtT0hnvjV4tSjtAWLGUUvPMEyoGjQpbybukd2rRBsAEHfPMuujOOiU9ITA0OAI3cXng8b+9/l1yUms1bePbtCsIPROqYLOFBU7i6nfFtJzcz6Ph6EwrH88Xk7UZoDLMNPTUjgA4PBqvW+Bld9HbpTiP5B5Dz9hB3BBS36q3rOCUiwZrEMavJVIpP9LKBAq+Yur00/Fy611VxNdpEPsTVhIMIw7CwngnLqkHbc+P3Mg1Xou+ArlwYBz66RvZO1O+ZpQYxodHhbV3PjtBjjlye1YRu7onL4drDnELiUNmHHkCdB3cJZIHVRI+oBS0QSTh5/IQ0999wVIUeP0ccnzpk3hZ/RyJSUgSGLSxvkTUn4GWeAid+rLLVRUgqD33zdyMlpQLVzM/yUAbWwaXsXcJIRZ72ys3HSUFb6ufww4wPDp55Sbwr9oQiwnIjK8oRe1j17DzAQVxiO8JXAsLRAMJGLIfLa+pWdUJJulJH+fhSnXJJWxyH46p4cu4yMR6+cfc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
